name: Kernel Build

on:
  push:
    branches: [master]
    tags:
        - release/*

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
          clean: false # Re-use artifacts from previous build
          submodules: recursive
    - name: Build Kernel
      run: make
    - name: Read Build Information
      id: read_build_info
      run: |
        echo "::set-output name=release::$(sed '1q;d' release.txt)"
        echo "::set-output name=dst::$(sed '1q;d' artifacts.txt)"
        echo "::set-output name=hdr::$(sed '2q;d' artifacts.txt)"
        echo "::set-output name=tools::$(sed '3q;d' artifacts.txt)"
        CHANGELOG=$(dpkg-parsechangelog -c 1 -l debian/changelog)
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: debs
        path: "*.deb"
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/release')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      run: |
        set -x
        assets=()
        for asset in ./*.deb; do
          assets + =("-a" "$asset")
        done
        tag_name=${GITHUB_REF#"refs/tags/"}
        release_name="${{ steps.read_build_info.outputs.release }}"
        changelog=$(dpkg-parsechangelog -c 1 -l debian/changelog)
        hub release create "${assets[@]}" -m "$release_name" -m "$changelog" "$tag_name" 
